from enum import Enum


class GameIconEnum(str, Enum):
    """MaterialIcons glyph names selectable in the icon picker. Must mirror ICON_CHOICES on the frontend."""

    casino = "casino"
    style = "style"
    extension = "extension"
    sports_esports = "sports-esports"
    psychology = "psychology"
    groups = "groups"
    theater_comedy = "theater-comedy"
    menu_book = "menu-book"
    sports_kabaddi = "sports-kabaddi"
    record_voice_over = "record-voice-over"
    gesture = "gesture"
    quiz = "quiz"
    sports_bar = "sports-bar"
    local_bar = "local-bar"
    local_fire_department = "local-fire-department"
    bolt = "bolt"
    rocket_launch = "rocket-launch"
    emoji_events = "emoji-events"
    star = "star"
    favorite = "favorite"
    lightbulb = "lightbulb"
    brush = "brush"
    music_note = "music-note"
    pets = "pets"
    sports_soccer = "sports-soccer"
    sports_basketball = "sports-basketball"
    flag = "flag"
    diamond = "diamond"
    celebration = "celebration"
    auto_awesome = "auto-awesome"
    cake = "cake"
    people = "people"
    public = "public"
    nightlife = "nightlife"
    attractions = "attractions"
    smart_toy = "smart-toy"
    science = "science"
    palette = "palette"
    headphones = "headphones"
    sports_mma = "sports-mma"
    anchor = "anchor"
    eco = "eco"
    ac_unit = "ac-unit"
    wb_sunny = "wb-sunny"
    coffee = "coffee"
